site_name: 并行计算基础 - 集群文档
repo_url: https://github.com/CircuitCoder/parallel-comp-docs
repo_name: parallel-comp-docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    logo: material/format-list-checks
  palette:
    primary: blue

nav:
  - 主页: index.md
  - 教程:
    - 集群使用初步: intro.md
  - 参考:
    - 集群配置: spec.md

extra_css:
  - styles/index.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
